# Site settings
title: cupid-wg
email: weng.luo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Wen Gang's Blog. Record learning notes and issue resolving experience collections, desire for your review comments^_^
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cupid-wg.bithub.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  cupid-wg

# Build settings
markdown: kramdown
